# **Token/Vector Embeddings**

NB: lecture note found here **[🔹 Lecture 10 Notes 🔹](lecture_10_notes.md)**

In [1]:
import torch
import tiktoken

**how token ids are converted to vector embeddings**

In [2]:
input_ids = torch.tensor([2, 3, 4, 1])

**for simplity we use 6 words vector dimension 3**

In [3]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embeddings_layer = torch.nn.Embedding(vocab_size, output_dim)

In [ ]:
# get the weight
print(embeddings_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [ ]:
# let get the te vector embedding of a particular token id
# the idea here is the embedding layer within itself is a lookup table so looking at token ids vector embedding
print(embeddings_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


so essentially what is happening here is:
![](images/L10_vec_s8.png)

In [8]:
# let get the vector embedding for the input_ids we declared earlier in cell 2
print("input ids:", input_ids)
print(embeddings_layer(input_ids))

input ids: tensor([2, 3, 4, 1])
tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)
