# **POSITIONAL EMBEDDINGS (ENCODING WORD POSITIONS)**

NB: lecture note found here **[🔹 Lecture 11 Notes 🔹](lecture_11_notes.md)**


In [3]:
import torch
import tiktoken
from custom_dataloader import create_dataloader_v1, GPTDatasetV1

In [4]:
with open("./data/the-verdict.txt", 'r', encoding="utf-8") as f:
    raw_text = f.read()

In [10]:
vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
token_embedding_layer.weight

Parameter containing:
tensor([[-0.1322, -1.0795,  0.4270,  ...,  1.6420, -0.4077, -0.5162],
        [-0.3450, -0.4059,  0.3453,  ...,  0.1215, -0.0983, -0.4092],
        [-1.8289,  0.0304, -0.6266,  ...,  0.2480, -2.8811,  1.5240],
        ...,
        [-0.5901,  0.9721, -1.0013,  ..., -1.3787,  0.2654,  0.5331],
        [ 0.1178, -0.6282,  0.4698,  ...,  0.8226,  2.7149,  0.1021],
        [ 1.1243,  1.0180, -0.4790,  ..., -1.7093, -0.0516, -1.0938]],
       requires_grad=True)

In [5]:
# instantiate the data loader
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)

In [6]:
print(f"Token IDs:\n {inputs}")
print(f"\nInput shape:\n {inputs.shape}")

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Input shape:
 torch.Size([8, 4])


In [11]:
# for each each in a batch, one embedding vector of `256` length is generated for each token in input
token_embedding = token_embedding_layer(inputs)
print(token_embedding.shape)
print(token_embedding)

torch.Size([8, 4, 256])
tensor([[[-3.2597e-01,  1.0433e+00,  2.5089e-02,  ..., -2.1286e-01,
          -8.5106e-01,  1.7701e+00],
         [-2.6661e-01, -2.5382e-01,  1.1152e+00,  ..., -4.0431e-01,
           2.9990e-02, -5.4534e-01],
         [-1.1300e+00, -3.4806e-01, -1.7051e+00,  ..., -8.5019e-01,
          -1.1515e-01, -6.7580e-01],
         [ 7.7264e-02, -2.5572e-01,  9.3243e-01,  ..., -3.7211e-01,
          -1.0206e+00, -8.5347e-01]],

        [[-8.3537e-01, -7.8160e-01,  3.0980e-01,  ...,  4.7375e-01,
           1.6835e-01, -5.9961e-01],
         [-2.2535e-02,  1.6937e-01, -6.8598e-01,  ...,  1.6706e+00,
           4.4325e-01,  7.8404e-01],
         [-1.1746e+00,  1.1598e+00, -1.9970e+00,  ...,  1.9518e-01,
           6.8821e-01,  8.9638e-01],
         [ 1.1152e+00, -4.0808e-01, -2.4209e+00,  ..., -8.7517e-02,
           5.8678e-01, -1.5194e+00]],

        [[-8.1297e-01, -4.4303e-01, -1.3537e+00,  ...,  1.3536e+00,
           1.8013e+00, -6.1993e-01],
         [-3.0130e-01, -1.0

In [12]:
context_length = max_length
# in position encoding, the number of rows should always be the same as the context length and also the columns should also match vector dimension
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [14]:
pos_embeddings = pos_embedding_layer(torch.arange(max_length))
print(pos_embeddings.shape)
print(pos_embeddings)

torch.Size([4, 256])
tensor([[-0.4073,  0.6113, -1.2282,  ..., -0.9778,  0.4884, -1.7974],
        [ 0.6138,  1.0506,  1.6585,  ..., -0.7342,  0.0286,  1.1887],
        [ 0.7795,  0.5807,  0.2142,  ...,  0.2365,  1.0706, -1.4617],
        [ 1.3325,  0.8733,  0.1519,  ...,  0.0089, -0.6072, -1.5975]],
       grad_fn=<EmbeddingBackward0>)
